### ISSUE TITLE
elife-metrics--prod update infrastructure failed due to AWS image ID AMI not exist

### ISSUE THREAD

**Issue by ali-tm-amin** [elifesciences/elife-metrics#252]
# Discription

I've tried to update the elife-metrics--prod infrastructure as increased the root disk size but the update has failed
`Resource handler returned message: "The image id '[ami-0ea409d43aa78d14f]' does not exist (Service: Ec2, Status Code: 400, Request ID: 3770d227-e4c8-4e07-abcf-6d014ae5ceba)" (RequestToken: 270a0f02-c213-5a75-d802-4b0894940db3, HandlerErrorCode: InvalidRequest)`

# Subtasks
- [ ] Create a new launch template or launch configuration using a valid AMI.
- [ ] Update your Auto Scaling group with the new launch template or launch configuration using the [update-auto-scaling-group](https://docs.aws.amazon.com/cli/latest/reference/autoscaling/update-auto-scaling-group.html) command.

# Definition of Done

- [ ] The infrastructure gets to update successfully after running `./bldr update_infrastructure:elife-metrics--prod `
